import Script from 'next/script'
import '../../styles/globals.css'
import '../../styles/globals.css'

export const metadata = {
  title: 'Create',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <meta charSet="utf-8" />
        <title>{metadata.title}</title>


        <Script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7215423654996673"
          crossorigin="anonymous"></Script>
        <meta name="google" content="nositelinkssearchbox" />
        <meta name="google" content="notranslate" />
      </head>
      <body>{children}</body>
    </html>
  )
}
