import '../../styles/globals.css'
import { Inter } from 'next/font/google'


export const metadata = {
  title: 'Create',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <meta charSet="utf-8" />
        <title>{metadata.title}</title>
      </head>
      <body>{children}</body>
    </html>
  )
}
